version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb0"
        ports:
            - 27017:27017
    mongodb2:
        image: mongo:latest
        container_name: "mongodb1"
        ports:
            - 27018:27017